name: "ScanAPI"
author: "@scanapi"
description: "Allows any developer to run ScanAPI using github actions"
branding:
  icon: "align-justify"
  color: "gray-dark"
inputs:
  scanapi_version:
      description: 'The ScanAPI version to be installed'
      required: false
      default: 'latest'
  arguments:
    description: "Desired arguments to run ScanAPI. Allow multiple parameters separated by spaces."
    required: true
    default: "--help"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.scanapi_version }}
    - ${{ inputs.arguments }}
